### ISSUE TITLE
Definir es esquema de la base de datos

### ISSUE THREAD

**Issue by CamiloCJ09** [Los-duros-de-DevOps-Web/inventory-management-for-smes#3]

**Comment by Johan794** [comment]
In order to use primsa you need to : 


1. Install prisma with **npm install prisma --save-dev**
2. Define a the folowing varibale in your .env file **POSTGRES_PRISMA_URL=postgresql://postgres:postgres@localhost:5432/imfs_db** Which is the url of the instance of postgres that comes from de docker-compose file. 
3. Once de db is running you need to run de commad **npx prisma db push** to set the schema defined
4. Install the prisma client using **npm install @prisma/client**
5. Then run **npx prisma generate**
6. Finally you can see the db and the entities using **npx prisma studio**

NOTE: The steps 3, 4 and 5 are only needed when there are changes in the scema 



All the info was retrived from:  https://vercel.com/guides/nextjs-prisma-postgres
